
spring:
  datasource:
    url: jdbc:mysql://192.168.222.145:3306/foodie-shop-dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    password: root
  redis:
    database: 0
    host: 192.168.222.145
    port: 6379
    password: noname

server:
  port: 8088
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #开启mybatsi 在控制台打印日志